### ISSUE TITLE
Remove `props` from output.

### ISSUE THREAD

**Issue by calebmer** [OpenJSX/babel-plugin-jsx#10]
Having the word `props` is a take from react and is not defined at all in the [jsx](https://facebook.github.io/jsx/) spec. Could this be changed to something more general? Either `attributes` or `properties`?

**Comment by NekR** [comment]
@calebmer what is the problem with `props` or `attrs`?

**Comment by calebmer** [comment]
Eh, it just feels a little too react-y. Also, after programming in languages like Haskell, I hate truncating variable names. It makes things way to hard to understand in the long term. Especially for newcomers. I'm closing this as I ended up writing my own implementation I'm hoping to land in babel, see babel/babel#3226.
